### ISSUE TITLE
Copilot Puppeteer headless browser

### ISSUE THREAD

**Issue by PalantirWizard** [mbrg/power-pwn#64]
Howdy folks,

When using puppeteer 22.10.0, there is no pop up as a headless chrome and got the error from the screenshot. Using the latest version of puppeteer, there is a blank white window pops up, then facing the same error from the screenshot

![image](https://github.com/user-attachments/assets/4d9cf70a-bcfa-43d5-a966-487bbb20adde)

![image](https://github.com/user-attachments/assets/0486545d-141c-4dca-a7e9-c8a97e3071a2)

![image](https://github.com/user-attachments/assets/6f5a99e8-7e9e-43da-b019-21a709923aba)

![image](https://github.com/user-attachments/assets/508a6d10-9c8c-4bdb-b99d-d44cd10a29c8)

Thanks!

**Comment by PalantirWizard** [comment]
![image](https://github.com/user-attachments/assets/dd2e93e0-5bac-42a2-8a9e-0dfcca9ac5ed)

**Comment by AvishaiEZen** [comment]
Hey @PalantirWizard,
We're checking this and will get back to you as soon as we can.

Thanks!

**Comment by ofrin-zen** [comment]
Hey @PalantirWizard ,
The headless white browser is a known problem with puppeteer - a fix exists and will be addressed shortly, however it is not the source of the error you see.
The error you encountered will be discussed in the [second issue](https://github.com/mbrg/power-pwn/issues/65) you opened.

Thanks!

**Comment by AvishaiEZen** [comment]
@PalantirWizard this issue has now been addressed in https://github.com/mbrg/power-pwn/pull/69 by using the default Chrome installation in Windows. We'll soon update this in the tool's documentation as well.

We'll update regarding the remaining problem you faced in [issue 65](https://github.com/mbrg/power-pwn/issues/65).

If you still have any issues, please let us know, thanks!
