### ISSUE TITLE
Vulnerable powerplatform apps and copilot apps

### ISSUE THREAD

**Issue by cheahengsoon** [mbrg/power-pwn#66]
Hi Team,
May I ask about request the sample vulnerable power platform apps or copilot apps?
Thank you.

**Comment by AvishaiEZen** [comment]
Hi @cheahengsoon, thanks for reaching out and your interest in powerpwn.
Could you please elaborate about this ask? Are you referring to getting vulnerable test power platform and copilots resources for testing with powerpwn?
Thanks

**Comment by AvishaiEZen** [comment]
Closing the issue, since there's been no response. Please let us know if you have any further Qs.
Thanks

**Comment by cheahengsoon** [comment]
> Hi @cheahengsoon, thanks for reaching out and your interest in powerpwn. Could you please elaborate about this ask? Are you referring to getting vulnerable test power platform and copilots resources for testing with powerpwn? Thanks

yes. I preferto getting the vulnerable test power platform and copilots resources.

**Comment by AvishaiEZen** [comment]
Discussed further [here](https://github.com/mbrg/power-pwn/issues/70).
